"""empty message

Revision ID: 746a90c429f3
Revises: fe2b2b18ebd2
Create Date: 2021-03-02 09:47:32.902564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746a90c429f3'
down_revision = 'fe2b2b18ebd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
